server:
    port: 8090
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

info:
    env: PROD

logging:
    config: config/logback-prod.xml

endpoints:
    sensitive: true
    info:
        sensitive: false